Requesting merge of group-related exercises.
rutefig/zklings pull request #15
Opened 2024-10-24 17:24 UTC by OwnerOfJK

The exercises that we added explore group theory and the different group axioms.

We focus on group theory to enable developers to get a better intuition for finite fields. This might be pretty low level but for devs who would like to better understand the math behind finite fields, this will be helpful.

The finite field specific exercises will be added next week.

2024-10-29 06:00 UTC, rutefig requested changes
For the math part, finite fields and modular arithmetic I think it can also be benefitial to have rust exercises but can we align better with what was already done: https://github.com/rutefig/zklings/blob/main/exercises/math/README.md

Instead of doing something from the beginning you can improve what is already done and add the rust exercises but respecting the structure that was done from the beginning pls. We can chat about this if you want

2024-11-04 10:18 UTC, OwnerOfJK commented on exercises/finite_fields/01_sets_and_groups/02_identity.rs
> +// Identity Property: There exists an element e in the group such that for every element a in the group, e * a = a * e = a.
Okay, let me think about it and we can discuss it tomorrow whenever you are available.

2024-11-05 09:12 UTC, rutefig commented on exercises/finite_fields/01_sets_and_groups/02_identity.rs
> +// Identity Property: There exists an element e in the group such that for every element a in the group, e * a = a * e = a.
I think we haven't discussed this, have you thought about it?

2024-11-05 18:34 UTC, OwnerOfJK commented on exercises/finite_fields/01_sets_and_groups/02_identity.rs
> +// Identity Property: There exists an element e in the group such that for every element a in the group, e * a = a * e = a.
I have been working on basically turning your previous modulo exercises into rust exercises.

I would then combine all exercises under a combined finite_fields folder rather than a math folder (math seems very general). I could also do it the other way around if you prefer.

So in that case the setup would be:

exercises/finite_fields/00_modulo
exercises/finite_fields/01_sets_and_groups
exercises/finite_fields/02_finite_fields

At the same time, I will adjust my exercises briefly to also use mod within the exercises to have a common theme that you also describe in the previous math README.

As for the additive operation, I wil also add it.

2024-11-20 16:09 UTC, rutefig commented on exercises/finite_fields/01_sets_and_groups/02_identity.rs
> +// Identity Property: There exists an element e in the group such that for every element a in the group, e * a = a * e = a.
Sorry about taking so much time on reviewing this again, it is also good if you re-request the review, because otherwise the reviewer cannot be sure if you are ready already with the changes. 
Regarding the markdown vs rust, I though about this in the beginning because I wanted to abstract the math module from any programming language, but since now we are also adding the protocols with rust I think we can include your changes regarding replacing the markdown exercises for the rust ones and later we can iterate on it, thank you for all the feedback 🙏🏼

2024-11-20 16:12 UTC, merged