Add proof generation and verification for circom exercises
rutefig/zklings pull request #8
Opened 2024-10-16 08:23 UTC by badgooooor

### Description

- Add proof generation and verification for circom exercises https://github.com/rutefig/zklings/issues/5
- In this pull request will included,
  - Proof generation and verification (Ref from [circom documentation](https://docs.circom.io/) and [snarkjs README](https://github.com/iden3/snarkjs) with  "powers of tau" ceremony setup (using power of 9, which satisfy circuit in exercise and takes about 10s to process everything)
  - Input file for each exercises named `<exercise_name>.json` for generating proof and verification
- Snapshot of added steps to `run_circom`
<img width="1196" alt="Screenshot 2567-10-16 at 11 51 31" src="https://github.com/user-attachments/assets/6afe726f-dc8a-4768-a95b-fa28c9f1507d">

2024-10-20 15:54 UTC, rutefig requested changes
I think this needs some refactor to make the code cleaner and maintainable for anyone, I would be really appreciated if you could do it pls 🙏🏼 other than that, great job 👏🏼

2024-10-20 15:54 UTC, rutefig commented on src/dev/new.rs
> +const README: &str = "# Rustlings 👽
Nice catch ahah but since you got this can you also change to ZKLings instead of Rustlings?

2024-10-20 15:54 UTC, rutefig commented on src/exercise_circom.rs
> +        return Ok(false);
Why is this not an Err instead of Ok?

2024-10-20 15:54 UTC, rutefig commented on src/exercise_circom.rs
> +        return Ok(false);
I think all of these blocks that are checking the success are redundant if you remove the `?` operator and return the result of the run function because this function already is returning `Result<bool>`

2024-10-21 01:24 UTC, badgooooor commented on src/dev/new.rs
> +const README: &str = "# Rustlings 👽
I fixed in some place I'm pretty confident that it won't affect other parts.

2024-10-21 01:28 UTC, badgooooor commented
Aside from a bit run-through while resolving issue, I've added stopping for exercise checking (in case there are any error while generating witness, generating proof and verifying proof)

![image](https://github.com/user-attachments/assets/636571cc-e8be-4742-ac0a-da385df7eff1)

2024-10-25 03:38 UTC, rutefig requested changes
There were some more improvements that came to my mind, happy to discuss and pair up if you want :)

2024-10-25 03:38 UTC, rutefig commented on src/time.rs
> +            // it prints '2'
Pls can you explain to me what is this comment about?

2024-10-25 03:38 UTC, rutefig commented on src/watch/notify_event.rs
> +        match input_event.kind {
I think this block of code could be more concise and clear, since there is a lot of repetition and nested matches

2024-10-25 04:18 UTC, badgooooor commented on src/exercise_circom.rs
> +                "9",
I think it would be nice to seperate ceremony process to another module and make it configurable. However, from the exercises in circom is more on smaller circuit, so setup ceremony process with low power such `9-10` is suitable for now.

For the implemented module I tried to make it based on type of file in exercise which result everything ends up in `CircomExercise`. I'd be good to refactor afterwards.

2024-10-25 07:04 UTC, badgooooor commented on src/exercise_circom.rs
> +                "9",
Update: Refactor this part as module called `CircuitCeremony`

2024-11-20 16:18 UTC, rutefig approved these changes
LGTM 👍🏼  thank you for taking some time and for all the improvements 🙏🏼

2024-11-20 16:18 UTC, merged